'''
Run concorde and LKH3 on all the the HardTSPLIB instances
Requires a working installation of concorde & LKH3
@author E. Vercesi, S. Gualandi, M. Mastrolilli, L. M. Gambardella
'''

'''
Packages
'''
import argparse, os, subprocess

'''
Main
'''
if __name__ == "__main__":
    # Parser
    parser = argparse.ArgumentParser()
    parser.add_argument("-concorde_path", type=str, help="Specify the path of the concorde executable")
    parser.add_argument("-lkh3_path", type=str, help="Specify the path of the LKH3 executable")
    parser.add_argument("-instance", type=str,  help="TSP instance in TSPLIB format")
    parser.add_argument("-seed", type=int, help="Seed", default=42)
    args = parser.parse_args()
    concorde_path = args.concorde_path
    lkh3_path = args.lkh3_path
    instance_path = args.instance
    seed = args.seed

    # Check if concorde is installed
    print("Checking if concorde exists")
    try:
        assert os.path.exists(concorde_path + "/concorde")
        print("\t Yes")
    except:
        raise ValueError("Concorde not found")

    # Check if LKH3 is installed
    print("Checking if LKH3 exists")
    try:
        assert os.path.exists(lkh3_path + "/LKH")
        print("\t Yes")
    except:
        raise ValueError("LKH3 not found, please install it from http://webhotel4.ruc.dk/~keld/research/LKH-3/ or specify the correct path")


    # Create a directory for the solution (if does not exist yes)
    try:
        os.makedirs('sol')
    except:
        pass

    # Create a directory where put all the intermediate files generated by concorde and the ones needed for LKH3 (if does not exists)
    try:
        os.makedirs('run')
    except:
        pass
    os.chdir("./run")


    # Set a name for the solution file (derived from the original name)
    solution_filename = "../sol/{}.sol".format(instance_path.split("/")[1].split(".")[0])

    # Add an extra-dot to the instance, as we are in the folder "run"
    if instance_path[0] == '.':
        instance_path = "." + instance_path
    else:
        instance_path = "../" + instance_path

    # Run concorde on the specify instance
    subprocess.run("{}/concorde -x -s {} -o {} {} > logC.log".format(concorde_path, seed, solution_filename, instance_path), shell=True)

    # Create a LKH3 par file in the run folder
    with open("LKH.par", "w") as f:
        f.write("PROBLEM_FILE = {}\n".format(instance_path))
        f.write("SEED = {}\n".format(seed))
        f.write("RUNS = 1\n")

    # Run LKH3 on the instance
    subprocess.run("{}/LKH LKH.par > logL.log".format(lkh3_path), shell=True)

    # Print the optimal value of Concorde
    print("------------------------------")
    print("Instance →", instance_path.split("/")[1])

    # Concorde solution is at line -3 of the log
    with open("logC.log", "r") as f:
        lines = f.readlines()
        print("\t Concorde solution:", lines[-3].strip())

    # LKH3 solution is at line -6 of the log
    with open("logL.log", "r") as f:
        lines = f.readlines()
        print("\t LKH3 solution:", lines[-6].strip())

